import { GoogleGenAI } from "@google/genai";
import { SYSTEM_PROMPT } from "./prompts";

export interface ChatMessagePayload {
  role: "user" | "assistant";
  content: string;
}

export async function askGemini(
  messages: ChatMessagePayload[],
  overrideModel?: string,
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY?.trim();
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured on the server");
  }

  const model = overrideModel || process.env.GEMINI_MODEL?.trim() || "gemini-3.6-flash";

  const ai = new GoogleGenAI({ apiKey });

  // Convert application messages to Gemini contents format
  const contents = messages.map((msg) => ({
    role: msg.role === "assistant" ? "model" : "user",
    parts: [{ text: msg.content }],
  }));

  const response = await ai.models.generateContent({
    model,
    contents,
    config: {
      systemInstruction: SYSTEM_PROMPT,
      temperature: 0.3,
    },
  });

  const text = response.text?.trim();
  if (!text) {
    throw new Error("No response generated by the AI model");
  }

  return text;
}
