import { overlay, pairText } from "@backend/i18n/catalog";
import { ids } from "./ids";
import type { DatabaseTables } from "@backend/types";

const daysAgo = (days: number, hours = 0) =>
  new Date(Date.now() - days * 86400000 - hours * 3600000).toISOString();

export function createSeed(): DatabaseTables {
  return {
    users: [
      {
        id: ids.users.customer,
        email: "maya@elevation.app",
        full_name: "Maya Chen",
        role: "customer",
        phone: "+1 415 555 0142",
        created_at: daysAgo(40),
        password_hash: "demo",
      },
      {
        id: ids.users.customerB,
        email: "jordan@elevation.app",
        full_name: "Jordan Hale",
        role: "customer",
        phone: "+1 646 555 0190",
        created_at: daysAgo(28),
        password_hash: "demo",
      },
      {
        id: ids.users.reviewer,
        email: "alex@elevation.app",
        full_name: "Alex Rivera",
        role: "reviewer",
        phone: null,
        created_at: daysAgo(90),
        password_hash: "demo",
      },
      {
        id: ids.users.manager,
        email: "priya@elevation.app",
        full_name: "Priya Shah",
        role: "manager",
        phone: null,
        created_at: daysAgo(120),
        password_hash: "demo",
      },
    ],
    application_types: [
      {
        id: ids.types.personal,
        key: "personal_loan",
        name: "Personal loan",
        description: "Unsecured personal credit for consolidation, expenses, or planned purchases.",
        sort_order: 1,
      },
      {
        id: ids.types.mortgage,
        key: "mortgage",
        name: "Mortgage",
        description: "Home purchase or refinance with property-backed underwriting.",
        sort_order: 2,
      },
      {
        id: ids.types.auto,
        key: "auto_loan",
        name: "Auto loan",
        description: "Vehicle financing with title and income verification.",
        sort_order: 3,
      },
      {
        id: ids.types.business,
        key: "business_loan",
        name: "Business loan",
        description: "Working capital or expansion credit for registered entities.",
        sort_order: 4,
      },
      {
        id: ids.types.credit,
        key: "credit_card",
        name: "Credit card",
        description: "Revolving consumer credit with identity and income checks.",
        sort_order: 5,
      },
    ],
    application_status: [
      {
        id: ids.status.draft,
        key: "draft",
        name: "Draft",
        description: "Application is being prepared.",
        sort_order: 0,
        pipeline_visible: false,
        is_terminal: false,
      },
      {
        id: ids.status.submitted,
        key: "submitted",
        name: "Submitted",
        description: "Packet received and queued.",
        sort_order: 1,
        pipeline_visible: true,
        is_terminal: false,
      },
      {
        id: ids.status.under_review,
        key: "under_review",
        name: "Under review",
        description: "A reviewer is evaluating the file.",
        sort_order: 2,
        pipeline_visible: true,
        is_terminal: false,
      },
      {
        id: ids.status.needs_resubmission,
        key: "needs_resubmission",
        name: "Needs resubmission",
        description: "Applicant must correct or replace documents.",
        sort_order: 3,
        pipeline_visible: true,
        is_terminal: false,
      },
      {
        id: ids.status.approved,
        key: "approved",
        name: "Approved",
        description: "Decision issued in favor of the applicant.",
        sort_order: 4,
        pipeline_visible: true,
        is_terminal: true,
      },
      {
        id: ids.status.rejected,
        key: "rejected",
        name: "Rejected",
        description: "Decision issued against the application.",
        sort_order: 5,
        pipeline_visible: true,
        is_terminal: true,
      },
    ],
    questions: [
      {
        id: ids.questions.loan_amount,
        key: "loan_amount",
        application_type_id: null,
        label: "Requested amount",
        helper_text: "The amount you want to borrow.",
        type: "number",
        options: null,
        required: true,
        sort_order: 10,
        placeholder: "25000",
      },
      {
        id: ids.questions.employment_status,
        key: "employment_status",
        application_type_id: null,
        label: "Employment status",
        helper_text: "Used to determine income documentation.",
        type: "select",
        options: [
          { value: "employed", label: "Employed" },
          { value: "self-employed", label: "Self-employed" },
          { value: "unemployed", label: "Unemployed" },
          { value: "retired", label: "Retired" },
        ],
        required: true,
        sort_order: 20,
        placeholder: null,
      },
      {
        id: ids.questions.employment_duration,
        key: "employment_duration_months",
        application_type_id: null,
        label: "Months at current role",
        helper_text: "How long you have been in your current position.",
        type: "number",
        options: null,
        required: true,
        sort_order: 30,
        placeholder: "18",
      },
      {
        id: ids.questions.annual_income,
        key: "annual_income",
        application_type_id: null,
        label: "Annual income",
        helper_text: "Gross annual income before tax.",
        type: "number",
        options: null,
        required: true,
        sort_order: 40,
        placeholder: "92000",
      },
      {
        id: ids.questions.residency_status,
        key: "residency_status",
        application_type_id: null,
        label: "Residency status",
        helper_text: null,
        type: "select",
        options: [
          { value: "citizen", label: "Citizen" },
          { value: "permanent_resident", label: "Permanent resident" },
          { value: "visa", label: "Visa / work permit" },
        ],
        required: true,
        sort_order: 50,
        placeholder: null,
      },
      {
        id: ids.questions.housing_status,
        key: "housing_status",
        application_type_id: null,
        label: "Housing",
        helper_text: null,
        type: "select",
        options: [
          { value: "own", label: "Own" },
          { value: "rent", label: "Rent" },
        ],
        required: true,
        sort_order: 60,
        placeholder: null,
      },
      {
        id: ids.questions.existing_debt,
        key: "has_existing_debt",
        application_type_id: null,
        label: "Do you have existing installment debt?",
        helper_text: null,
        type: "boolean",
        options: null,
        required: true,
        sort_order: 70,
        placeholder: null,
      },
      {
        id: ids.questions.down_payment,
        key: "down_payment_percent",
        application_type_id: ids.types.mortgage,
        label: "Down payment (%)",
        helper_text: "Percentage of purchase price paid upfront.",
        type: "number",
        options: null,
        required: true,
        sort_order: 80,
        placeholder: "20",
      },
      {
        id: ids.questions.property_type,
        key: "property_type",
        application_type_id: ids.types.mortgage,
        label: "Property type",
        helper_text: null,
        type: "select",
        options: [
          { value: "single_family", label: "Single family" },
          { value: "condo", label: "Condo" },
          { value: "multi", label: "Multi-unit" },
        ],
        required: true,
        sort_order: 90,
        placeholder: null,
      },
      {
        id: ids.questions.vehicle_year,
        key: "vehicle_year",
        application_type_id: ids.types.auto,
        label: "Vehicle year",
        helper_text: null,
        type: "number",
        options: null,
        required: true,
        sort_order: 80,
        placeholder: "2022",
      },
      {
        id: ids.questions.business_years,
        key: "business_years",
        application_type_id: ids.types.business,
        label: "Years in operation",
        helper_text: null,
        type: "number",
        options: null,
        required: true,
        sort_order: 80,
        placeholder: "4",
      },
      {
        id: ids.questions.business_entity,
        key: "business_entity",
        application_type_id: ids.types.business,
        label: "Entity type",
        helper_text: null,
        type: "select",
        options: [
          { value: "sole", label: "Sole proprietor" },
          { value: "llc", label: "LLC" },
          { value: "corp", label: "Corporation" },
        ],
        required: true,
        sort_order: 90,
        placeholder: null,
      },
      {
        id: ids.questions.credit_purpose,
        key: "credit_purpose",
        application_type_id: ids.types.credit,
        label: "Primary use",
        helper_text: null,
        type: "select",
        options: [
          { value: "everyday", label: "Everyday spending" },
          { value: "travel", label: "Travel" },
          { value: "build_credit", label: "Build credit" },
        ],
        required: true,
        sort_order: 80,
        placeholder: null,
      },
    ],
    question_visibility_rules: [
      {
        id: "vis-0001-0000-4000-8000-000000000001",
        question_id: ids.questions.employment_duration,
        conditions: {
          combinator: "or",
          conditions: [
            { questionKey: "employment_status", operator: "eq", value: "employed" },
            { questionKey: "employment_status", operator: "eq", value: "self-employed" },
          ],
        },
      },
    ],
    document_types: [
      {
        id: ids.docs.government_id,
        key: "government_id",
        name: "Government ID",
        description: "Passport or national ID, all corners visible.",
        accepted_mime_types: ["application/pdf", "image/jpeg", "image/png"],
        max_size_bytes: 8 * 1024 * 1024,
        validation_hints: ["Face must be unobstructed", "Expiry date must be readable"],
      },
      {
        id: ids.docs.proof_of_address,
        key: "proof_of_address",
        name: "Proof of address",
        description: "Utility bill or bank letter issued in the last 90 days.",
        accepted_mime_types: ["application/pdf", "image/jpeg", "image/png"],
        max_size_bytes: 8 * 1024 * 1024,
        validation_hints: ["Name must match the applicant", "Issue date within 90 days"],
      },
      {
        id: ids.docs.proof_of_income,
        key: "proof_of_income",
        name: "Proof of income",
        description: "Recent payslips or equivalent income evidence.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 10 * 1024 * 1024,
        validation_hints: ["At least one full pay period"],
      },
      {
        id: ids.docs.bank_statements,
        key: "bank_statements",
        name: "Bank statements",
        description: "Last 90 days from the primary account.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 12 * 1024 * 1024,
        validation_hints: ["All pages included", "Account holder name visible"],
      },
      {
        id: ids.docs.tax_returns,
        key: "tax_returns",
        name: "Tax returns",
        description: "Most recent personal or business tax filing.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 12 * 1024 * 1024,
        validation_hints: ["Complete return, not a summary page"],
      },
      {
        id: ids.docs.employment_letter,
        key: "employment_letter",
        name: "Employment letter",
        description: "Letter confirming role, tenure, and compensation.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 8 * 1024 * 1024,
        validation_hints: ["Must be on company letterhead"],
      },
      {
        id: ids.docs.property_appraisal,
        key: "property_appraisal",
        name: "Property appraisal",
        description: "Independent valuation for the subject property.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 15 * 1024 * 1024,
        validation_hints: ["Must include appraiser license"],
      },
      {
        id: ids.docs.title_deed,
        key: "title_deed",
        name: "Title deed",
        description: "Current deed or purchase agreement.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 10 * 1024 * 1024,
        validation_hints: ["Legal description must be complete"],
      },
      {
        id: ids.docs.vehicle_title,
        key: "vehicle_title",
        name: "Vehicle title",
        description: "Title or bill of sale for the financed vehicle.",
        accepted_mime_types: ["application/pdf", "image/jpeg", "image/png"],
        max_size_bytes: 8 * 1024 * 1024,
        validation_hints: ["VIN must be readable"],
      },
      {
        id: ids.docs.business_registration,
        key: "business_registration",
        name: "Business registration",
        description: "Certificate of registration or good standing.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 8 * 1024 * 1024,
        validation_hints: ["Entity name must match application"],
      },
      {
        id: ids.docs.articles,
        key: "articles_of_incorporation",
        name: "Articles of incorporation",
        description: "Formation documents for LLC or corporation.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 10 * 1024 * 1024,
        validation_hints: ["Signed by an authorized officer"],
      },
      {
        id: ids.docs.void_check,
        key: "void_check",
        name: "Voided check",
        description: "For disbursement account verification.",
        accepted_mime_types: ["application/pdf", "image/jpeg", "image/png"],
        max_size_bytes: 6 * 1024 * 1024,
        validation_hints: ["Routing and account numbers visible"],
      },
      {
        id: ids.docs.credit_auth,
        key: "credit_authorization",
        name: "Credit authorization",
        description: "Signed consent for a consumer credit pull.",
        accepted_mime_types: ["application/pdf"],
        max_size_bytes: 6 * 1024 * 1024,
        validation_hints: ["Wet or compliant e-signature required"],
      },
    ],
    requirement_rules: [
      { id: "rule-01", document_type_id: ids.docs.government_id, application_type_id: null, conditions: null, required: true },
      { id: "rule-02", document_type_id: ids.docs.proof_of_address, application_type_id: null, conditions: null, required: true },
      { id: "rule-03", document_type_id: ids.docs.proof_of_income, application_type_id: null, conditions: null, required: true },
      { id: "rule-04", document_type_id: ids.docs.bank_statements, application_type_id: null, conditions: null, required: true },
      {
        id: "rule-05",
        document_type_id: ids.docs.tax_returns,
        application_type_id: null,
        conditions: {
          combinator: "or",
          conditions: [
            { questionKey: "employment_status", operator: "eq", value: "self-employed" },
            { questionKey: "employment_status", operator: "eq", value: "retired" },
          ],
        },
        required: true,
      },
      {
        id: "rule-06",
        document_type_id: ids.docs.employment_letter,
        application_type_id: null,
        conditions: {
          combinator: "and",
          conditions: [{ questionKey: "employment_status", operator: "eq", value: "employed" }],
        },
        required: true,
      },
      {
        id: "rule-07",
        document_type_id: ids.docs.void_check,
        application_type_id: null,
        conditions: {
          combinator: "and",
          conditions: [{ questionKey: "loan_amount", operator: "gte", value: 15000 }],
        },
        required: true,
      },
      { id: "rule-08", document_type_id: ids.docs.property_appraisal, application_type_id: ids.types.mortgage, conditions: null, required: true },
      { id: "rule-09", document_type_id: ids.docs.title_deed, application_type_id: ids.types.mortgage, conditions: null, required: true },
      { id: "rule-10", document_type_id: ids.docs.vehicle_title, application_type_id: ids.types.auto, conditions: null, required: true },
      { id: "rule-11", document_type_id: ids.docs.business_registration, application_type_id: ids.types.business, conditions: null, required: true },
      {
        id: "rule-12",
        document_type_id: ids.docs.articles,
        application_type_id: ids.types.business,
        conditions: {
          combinator: "and",
          conditions: [{ questionKey: "business_entity", operator: "in", value: ["llc", "corp"] }],
        },
        required: true,
      },
      { id: "rule-13", document_type_id: ids.docs.credit_auth, application_type_id: ids.types.credit, conditions: null, required: true },
    ],
    applications: [
      {
        id: ids.applications.personalReview,
        user_id: ids.users.customer,
        type_id: ids.types.personal,
        current_status_id: ids.status.under_review,
        created_at: daysAgo(6, 4),
        updated_at: daysAgo(1, 2),
        submitted_at: daysAgo(5, 8),
      },
      {
        id: ids.applications.mortgageApproved,
        user_id: ids.users.customerB,
        type_id: ids.types.mortgage,
        current_status_id: ids.status.approved,
        created_at: daysAgo(21),
        updated_at: daysAgo(8),
        submitted_at: daysAgo(18),
      },
      {
        id: ids.applications.autoRejected,
        user_id: ids.users.customer,
        type_id: ids.types.auto,
        current_status_id: ids.status.needs_resubmission,
        created_at: daysAgo(9),
        updated_at: daysAgo(1),
        submitted_at: daysAgo(8),
      },
      {
        id: ids.applications.businessSubmitted,
        user_id: ids.users.customerB,
        type_id: ids.types.business,
        current_status_id: ids.status.submitted,
        created_at: daysAgo(2, 3),
        updated_at: daysAgo(2, 1),
        submitted_at: daysAgo(2, 1),
      },
    ],
    application_answers: [
      ans(ids.applications.personalReview, ids.questions.loan_amount, 18000),
      ans(ids.applications.personalReview, ids.questions.employment_status, "employed"),
      ans(ids.applications.personalReview, ids.questions.employment_duration, 26),
      ans(ids.applications.personalReview, ids.questions.annual_income, 94000),
      ans(ids.applications.personalReview, ids.questions.residency_status, "citizen"),
      ans(ids.applications.personalReview, ids.questions.housing_status, "rent"),
      ans(ids.applications.personalReview, ids.questions.existing_debt, true),
      ans(ids.applications.mortgageApproved, ids.questions.loan_amount, 420000),
      ans(ids.applications.mortgageApproved, ids.questions.employment_status, "employed"),
      ans(ids.applications.mortgageApproved, ids.questions.employment_duration, 48),
      ans(ids.applications.mortgageApproved, ids.questions.annual_income, 168000),
      ans(ids.applications.mortgageApproved, ids.questions.residency_status, "citizen"),
      ans(ids.applications.mortgageApproved, ids.questions.housing_status, "own"),
      ans(ids.applications.mortgageApproved, ids.questions.existing_debt, false),
      ans(ids.applications.mortgageApproved, ids.questions.down_payment, 20),
      ans(ids.applications.mortgageApproved, ids.questions.property_type, "single_family"),
      ans(ids.applications.autoRejected, ids.questions.loan_amount, 24000),
      ans(ids.applications.autoRejected, ids.questions.employment_status, "self-employed"),
      ans(ids.applications.autoRejected, ids.questions.employment_duration, 11),
      ans(ids.applications.autoRejected, ids.questions.annual_income, 41000),
      ans(ids.applications.autoRejected, ids.questions.residency_status, "visa"),
      ans(ids.applications.autoRejected, ids.questions.housing_status, "rent"),
      ans(ids.applications.autoRejected, ids.questions.existing_debt, true),
      ans(ids.applications.autoRejected, ids.questions.vehicle_year, 2016),
      ans(ids.applications.businessSubmitted, ids.questions.loan_amount, 75000),
      ans(ids.applications.businessSubmitted, ids.questions.employment_status, "self-employed"),
      ans(ids.applications.businessSubmitted, ids.questions.employment_duration, 36),
      ans(ids.applications.businessSubmitted, ids.questions.annual_income, 210000),
      ans(ids.applications.businessSubmitted, ids.questions.residency_status, "permanent_resident"),
      ans(ids.applications.businessSubmitted, ids.questions.housing_status, "own"),
      ans(ids.applications.businessSubmitted, ids.questions.existing_debt, false),
      ans(ids.applications.businessSubmitted, ids.questions.business_years, 5),
      ans(ids.applications.businessSubmitted, ids.questions.business_entity, "llc"),
    ],
    application_status_events: [
      event(ids.applications.personalReview, ids.status.submitted, ids.users.customer, pairText(overlay("Application submitted")), daysAgo(5, 8)),
      event(ids.applications.personalReview, ids.status.under_review, ids.users.reviewer, pairText(overlay("Assigned to review queue")), daysAgo(1, 2)),
      event(ids.applications.mortgageApproved, ids.status.submitted, ids.users.customerB, pairText(overlay("Application submitted")), daysAgo(18)),
      event(ids.applications.mortgageApproved, ids.status.under_review, ids.users.reviewer, pairText(overlay("File opened")), daysAgo(14)),
      event(ids.applications.mortgageApproved, ids.status.approved, ids.users.manager, pairText(overlay("Income and title checks cleared")), daysAgo(8)),
      event(ids.applications.autoRejected, ids.status.submitted, ids.users.customer, pairText(overlay("Application submitted")), daysAgo(8)),
      event(ids.applications.autoRejected, ids.status.under_review, ids.users.reviewer, pairText(overlay("Manual review started")), daysAgo(4)),
      event(ids.applications.autoRejected, ids.status.needs_resubmission, ids.users.reviewer, pairText(overlay("Vehicle title is unreadable and income docs do not cover the stated period.")), daysAgo(1)),
      event(ids.applications.businessSubmitted, ids.status.submitted, ids.users.customerB, pairText(overlay("Application submitted")), daysAgo(2, 1)),
    ],
    documents: [
      doc("doc-1", ids.applications.personalReview, ids.docs.government_id, "maya-passport.pdf", "success", daysAgo(5, 7)),
      doc("doc-2", ids.applications.personalReview, ids.docs.proof_of_address, "utility-april.pdf", "success", daysAgo(5, 6)),
      doc("doc-3", ids.applications.personalReview, ids.docs.proof_of_income, "payslips-q1.pdf", "success", daysAgo(5, 6)),
      doc("doc-4", ids.applications.personalReview, ids.docs.bank_statements, "chase-90d.pdf", "pending", daysAgo(1, 3)),
      doc("doc-5", ids.applications.personalReview, ids.docs.employment_letter, "acme-employment.pdf", "success", daysAgo(5, 5)),
      doc("doc-6", ids.applications.personalReview, ids.docs.void_check, "void-check.png", "success", daysAgo(5, 5)),
      doc("doc-7", ids.applications.mortgageApproved, ids.docs.government_id, "jordan-id.pdf", "success", daysAgo(18)),
      doc("doc-8", ids.applications.mortgageApproved, ids.docs.proof_of_address, "property-tax.pdf", "success", daysAgo(18)),
      doc("doc-9", ids.applications.mortgageApproved, ids.docs.title_deed, "deed.pdf", "success", daysAgo(17)),
      doc("doc-10", ids.applications.autoRejected, ids.docs.government_id, "maya-id.pdf", "success", daysAgo(8)),
      doc("doc-11", ids.applications.autoRejected, ids.docs.vehicle_title, "title-blur.jpg", "error", daysAgo(8), [
        { code: "quality_failed", message: pairText(overlay("VIN and issuing authority are not readable.")) },
      ]),
      doc("doc-12", ids.applications.autoRejected, ids.docs.tax_returns, "return-sample.pdf", "error", daysAgo(8), [
        { code: "quality_failed", message: pairText(overlay("Filing year and AGI could not be extracted.")) },
      ]),
      doc("doc-13", ids.applications.businessSubmitted, ids.docs.government_id, "jordan-passport.pdf", "success", daysAgo(2)),
      doc("doc-14", ids.applications.businessSubmitted, ids.docs.business_registration, "llc-certificate.pdf", "success", daysAgo(2)),
      doc("doc-15", ids.applications.businessSubmitted, ids.docs.articles, "articles.pdf", "pending", daysAgo(2)),
    ],
    reviews: [
      {
        id: "rev-1",
        application_id: ids.applications.mortgageApproved,
        reviewer_id: ids.users.manager,
        decision: "approve",
        rationale: pairText(overlay("Income, reserves, and title package meet policy. Appraisal variance within tolerance.")),
        ai_recommendation: {
          action: "approve",
          confidence: 0.91,
          rationale: pairText(overlay("Complete packet with aligned income and no open flags.")),
          risk_score: 16,
          factors: [
            { code: "complete_packet", label: pairText(overlay("All required documents passed")), weight: 0.24, direction: "positive" },
          ],
        },
        created_at: daysAgo(8),
      },
      {
        id: "rev-2",
        application_id: ids.applications.autoRejected,
        reviewer_id: ids.users.reviewer,
        decision: "request_resubmission",
        rationale: pairText(overlay("Vehicle title is unreadable and the tax return appears incomplete. Please re-upload both documents.")),
        ai_recommendation: {
          action: "reject",
          confidence: 0.74,
          rationale: pairText(overlay("Document quality failures and elevated affordability risk.")),
          risk_score: 71,
          factors: [
            { code: "validation_errors", label: pairText(overlay("2 documents failed automated validation")), weight: 0.26, direction: "negative" },
          ],
        },
        created_at: daysAgo(1),
      },
    ],
    flags: [
      {
        id: "flag-1",
        application_id: ids.applications.autoRejected,
        document_id: "doc-11",
        severity: "high",
        code: "unreadable_title",
        message: pairText(overlay("Vehicle title image failed OCR. VIN cannot be matched to the application.")),
        created_at: daysAgo(4),
        resolved_at: null,
      },
      {
        id: "flag-2",
        application_id: ids.applications.autoRejected,
        document_id: "doc-12",
        severity: "medium",
        code: "income_mismatch",
        message: pairText(overlay("Stated income is not supported by the uploaded tax filing.")),
        created_at: daysAgo(4),
        resolved_at: null,
      },
      {
        id: "flag-3",
        application_id: ids.applications.personalReview,
        document_id: "doc-4",
        severity: "low",
        code: "statement_pending",
        message: pairText(overlay("Bank statement validation is still running.")),
        created_at: daysAgo(1, 3),
        resolved_at: null,
      },
      {
        id: "flag-4",
        application_id: ids.applications.businessSubmitted,
        document_id: null,
        severity: "medium",
        code: "new_entity_geo",
        message: pairText(overlay("Registered address differs from the applicant residential address.")),
        created_at: daysAgo(2),
        resolved_at: null,
      },
    ],
    activity_events: [
      {
        id: "act-1",
        actor_id: ids.users.customer,
        application_id: ids.applications.personalReview,
        type: "application.submitted",
        message: pairText(overlay("Maya Chen submitted a personal loan application.")),
        created_at: daysAgo(5, 8),
      },
      {
        id: "act-2",
        actor_id: ids.users.reviewer,
        application_id: ids.applications.personalReview,
        type: "application.review_started",
        message: pairText(overlay("Alex Rivera opened Maya Chen’s personal loan file.")),
        created_at: daysAgo(1, 2),
      },
      {
        id: "act-3",
        actor_id: ids.users.manager,
        application_id: ids.applications.mortgageApproved,
        type: "application.approved",
        message: pairText(overlay("Priya Shah approved Jordan Hale’s mortgage.")),
        created_at: daysAgo(8),
      },
      {
        id: "act-4",
        actor_id: ids.users.reviewer,
        application_id: ids.applications.autoRejected,
        type: "application.resubmission_requested",
        message: pairText(overlay("Alex Rivera requested new documents on Maya Chen’s auto loan.")),
        created_at: daysAgo(1),
      },
      {
        id: "act-5",
        actor_id: ids.users.customerB,
        application_id: ids.applications.businessSubmitted,
        type: "application.submitted",
        message: pairText(overlay("Jordan Hale submitted a business loan application.")),
        created_at: daysAgo(2, 1),
      },
    ],
  };
}

function ans(application_id: string, question_id: string, value: string | number | boolean) {
  return {
    id: `${application_id}:${question_id}`,
    application_id,
    question_id,
    value,
    updated_at: new Date().toISOString(),
  };
}

function event(
  application_id: string,
  status_id: string,
  actor_id: string,
  note: string,
  created_at: string,
) {
  return {
    id: `${application_id}:${status_id}:${created_at}`,
    application_id,
    status_id,
    actor_id,
    note,
    created_at,
  };
}

function doc(
  id: string,
  application_id: string,
  document_type_id: string,
  file_name: string,
  validation_status: "idle" | "pending" | "success" | "error",
  uploaded_at: string,
  validation_issues: Array<{ code: string; message: string }> = [],
) {
  return {
    id,
    application_id,
    document_type_id,
    file_name,
    file_path: `uploads/${application_id}/${file_name}`,
    mime_type: file_name.endsWith(".png") || file_name.endsWith(".jpg") ? "image/jpeg" : "application/pdf",
    size_bytes: validation_status === "error" ? 8200 : 248000,
    validation_status,
    validation_issues,
    uploaded_at,
    validated_at: validation_status === "pending" || validation_status === "idle" ? null : uploaded_at,
  };
}
